# Generated by Django 5.0.6 on 2024-05-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userssection', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shareable_url',
        ),
    ]
