# Generated by Django 5.0.6 on 2024-05-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userssection', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
